@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

<style>
classDiagram {
  BackGroundColor white
  LineThickness 1
  LineColor black
}
</style>

entity "CUSTOMERS" as customers {
* customer_id : NUMBER <<generated>>
---
* surname : VARCHAR(50)
* email : VARCHAR(35)
}

entity "ADDRESSES" as addresses {
* address_id : NUMBER <<generated>>
---
* customer_id : NUMBER
street : VARCHAR(250)
number : VARCHAR(5)
city : VARCHAR(250)
country : VARCHAR(250)
zip_code : VARCHAR(5)
}

customers ||..o{ addresses
customers -r[hidden]-> addresses



entity "CUSTOMER_EVENTS" as customer_events {
* customer_event_id : NUMBER <<generated>>
---
* key : VARCHAR(500)
value : VARCHAR
}

customers -d[hidden]- customer_events

@enduml
