@startuml
!theme plain

actor actor as "Actor"
rectangle validate as "Validate"
rectangle business_logic as "Business Logic"
rectangle store_data as "Store\nData"
database store as "Store"
hexagon entity_stored as "Entity\nStored"
queue event_broker as "Event Broker"

actor -> validate
validate -> business_logic
business_logic -> store_data
store_data .. store
store_data -> entity_stored
note on link
  If there's a failure
  at this point the event
  is never published
end note
entity_stored .. event_broker



@enduml